version: '3'
services:
  app:
    build: .
    ports: 
      - "8080:8080"
#    depends_on:
#      - db

#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    volumes:
#      - mysql_data:/var/lib/mysql
#volumes:
#  mysql_data: {}
